"$schema" = 'https://starship.rs/config-schema.json'

palette = ""

[character]
error_symbol = "[[󰄛](red) ❯](peach)"
success_symbol = "[[󰄛](green) ❯](peach)"
vimcmd_symbol = "[󰄛 ❮](subtext1)"

[directory]
style = "bold lavender"
truncation_length = 4

[git_branch]
style = "bold mauve"
