description: "Define and run multi-container applications with Docker"
label: "Docker Compose"
name: "docker-compose"
repository: "extra"
repository_url: "https://archlinux.org/packages/extra/x86_64/docker-compose/"
source_url: "https://github.com/docker/compose/"
url: "https://www.docker.com/"
